apiVersion: apps/v1
kind: Deployment
metadata:
  name: tc-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tc-ms
  template:
    metadata:
      labels:
        app: tc-ms
    spec:
      containers:
        - name: tc-ms-server
          image: ghcr.io/tipapornc/tc_ms
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tc-ms-service
  labels:
    app: tc-ms-service
spec:
  selector:
    app: tc-ms
  ports:
    - name: web-port
      protocol: TCP
      port: 8081
      targetPort: 80
  type: ClusterIP            